---
title: "Final_project_heatmap"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Figure 3I

```{r}
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("gplots")) install.packages("gplots")
library(dplyr)
library(gplots)
library(tidyverse)

new_cd <- read.csv("https://raw.githubusercontent.com/bbista/BCBX546_Final_project/master/annotated.diff.csv?token=Ah7pvMuMiwP776ouqap0F8El0s6SCygmks5cDcNWwA%3D%3D",stringsAsFactors = F) #import file

forheat<-data.frame(Gene_id=character(), ID_Symbol=character(),	H2O_young=character(),	H2O_aged=character(),	PQ_young=character(),	PQ_aged=character(), stringsAsFactors = F)

for (i in unique(new_cd$gene_id)){
  f<-new_cd[new_cd$gene_id==i,]
  forheat[nrow(forheat)+1,] <- c(unique(f$gene_id),unique(f$gene_short_name), unique(f$value_1[f$sample_1=="H20Y"]), unique(f$value_1[f$sample_1=="H2OO"]), unique(f$value_2[f$sample_2=="PQY"]), unique(f$value_2[f$sample_2=="PQO"]) )
   
} # melt data and extract variables with unique gene_id corresponding to 4 conditions

forheat <- transform(forheat,H2O_young=as.numeric(H2O_young),H2O_aged=as.numeric(H2O_aged),PQ_young=as.numeric(PQ_young),PQ_aged=as.numeric(PQ_aged) ) # transform character to numeric

heat<-filter(forheat,ID_Symbol !="NA" & rowSums(forheat[3:6]) != 0) # filter data to get rid of ID_Symbol without names and FPKM in 4 conditions all with value equal to 0

heatmap <- select (heat, 3:6)
heatmap_matrix <- data.matrix(heatmap) +1
log2_matrix <- log2 (heatmap_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))
# couldn't save the images, so I use printscreen to save all the images after they are created 
foo <- cbind(log2_matrix, clusterID= mycl)
cluster <- foo[hr$order,]
write.table(cluster, file = "cluster_data.csv", sep = ",")
```
## Fig 4K
1 import file, sort and generated files based on P450 categories
```{r}
library(readxl)
table_S1 <- read_excel("table_S1.xlsx", sheet = "List 10")
P450 <-table_S1
P450 <- select(P450,5:10)
colnames(P450)[6] <-"Mito_clan"
P450_sort <- arrange(P450,desc(Mito_clan))

uniq_P450<- unique(unlist(P450_sort$Mito_clan))
uniq_P450
for (i in 1:length(uniq_P450)){
  filename <- paste("clan",i,".txt", sep="")
  print(filename)
  P450_sort %>% filter(Mito_clan==uniq_P450[i]) %>%
    write.csv(filename)
}
Mito_clan <- read.csv("clan1.txt")
clan2 <- read.csv("clan4.txt")
clan3 <- read.csv("clan3.txt")
clan4 <- read.csv("clan2.txt")
```

2 Creat heatmaps for each subset of P450 genes expression

```{r}
M_hm <- select(Mito_clan,2:5)
M_hm_matrix <- data.matrix(M_hm) +1
log2_matrix <- log2 (M_hm_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))

C2_hm <- select(clan2,2:5)
C2_hm_matrix <- data.matrix(C2_hm) +1
log2_matrix <- log2 (C2_hm_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))

C2_new <- filter (clan2, H2O.Young > 2)
C2_new_hm <- select(C2_new,2:5)
C2_new_hm_matrix <- data.matrix(C2_new_hm) +1
log2_matrix <- log2 (C2_new_hm_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))


C3_hm <- select(clan3,2:5)
C3_hm_matrix <- data.matrix(C3_hm) +1
log2_matrix <- log2 (C3_hm_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))

C4_hm <- clan4[3:33,2:5]
C4_hm_matrix <- data.matrix(C4_hm) +1
log2_matrix <- log2 (C4_hm_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))


```

3 creat 1 heatmap for the whole P450 data set

```{r}
#library (ggplot2)
colnames(P450_sort) [1:4] <- c("H2O_young","H2O_aged","PQ_young","PQ_aged")
P450_sort <- filter (P450_sort,H2O_young != "NA" & rowSums(P450_sort[1:4]) != 0)

P450_hm <- P450_sort[1:4]
P450_hm_matrix <- data.matrix(P450_hm) +1
log2_matrix <- log2 (P450_hm_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
par("mar")
par(mar=c(1,1,1,1))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))


```


## Fig.4J

```{r}
table_S1 <- read_excel("table_S1.xlsx", sheet = "List 9")
GST <- table_S1
GST_sort <- select (GST, 1,22,23,24,25)
Delta <- slice (GST_sort,1:11)
Epsilon <- slice (GST_sort,12:25)
Others <- slice (GST_sort, 26:38)

Delta_hm <- Delta[2:5]
Delta_hm_matrix <- data.matrix(Delta_hm) +1
log2_matrix <- log2 (Delta_hm_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))


Epsilon_hm <- Epsilon[2:5]
Epsilon_hm_matrix <- data.matrix(Epsilon_hm) +1
log2_matrix <- log2 (Epsilon_hm_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))


Other_hm <- Others[2:5]
Other_hm_matrix <- data.matrix(Other_hm) +1
log2_matrix <- log2 (Other_hm_matrix)
hr <- hclust(as.dist(1-cor(t(log2_matrix), method = "pearson")), method = "complete")
mycl <- cutree(hr, h=max(hr$height/1.5))
clusterCols <- rainbow(length(unique(mycl)))
myClusterSideBar <- clusterCols[mycl]
myheatcol <- rev(redblue(75))
heatmap.2(log2_matrix, main="Hierarchical Cluster", Rowv=as.dendrogram(hr), dendrogram = "row", Colv=NA,  scale="row", col=myheatcol,  density.info="none", trace="none", RowSideColors= myClusterSideBar, margins = c(1,1))

```
